/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetointegradorfarmacia.view;

import com.mycompany.projetointegradorfarmacia.utils.Validadora;
import com.mycompany.projetointegradorfarmacia.model.Cliente;
import com.mycompany.projetointegradorfarmacia.controller.ClienteController;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Classe responsável pela interface de cadastro, manutenção e consulta de
 * clientes
 *
 * @author mariana.spinelli
 * @since 2021.05.12
 * @version 1.0
 *
 */
public class CadastroClienteView extends javax.swing.JFrame {

    public String modoTela = "criação";
    Cliente objCliente;

    public CadastroClienteView() {
        initComponents();
        objCliente = new Cliente();
        setLocationRelativeTo(null);
        listarClientes(); //carrega todos os clientes cadastrados na base de dados
    }

    public CadastroClienteView(Cliente c) {
        initComponents();
        this.objCliente = c;
        this.ftxCPF.setText(c.getCPF());
        this.txtNome.setText(c.getNomeCliente());
        this.cboGenero.setSelectedItem(c);
        this.cboEstadoCivil.setSelectedItem(c);
        this.ftxTelefone.setText(c.getTelCliente());
        this.jDateChooser1.setDate(c.getDataNascimento());
        //this.ftxNascimento.setText(c.getDataNascimento());
        this.txtEmail.setText(c.getEmailCliente());
        this.txtEndereco.setText(c.getEnderecoCliente());
        this.txtBairro.setText(c.getBairroCliente());
        this.txtCidade.setText(c.getCidadeCliente());
        this.cboEstado.setSelectedItem(c);
        this.ftxCepCliente.setText(c.getCEPcliente());

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        ftxCPF = new javax.swing.JFormattedTextField();
        btnConsultarCPF = new javax.swing.JButton();
        lblGenero = new javax.swing.JLabel();
        cboGenero = new javax.swing.JComboBox<>();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        ftxTelefone = new javax.swing.JFormattedTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        cboEstadoCivil = new javax.swing.JComboBox<>();
        lblDataNascimento = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        lblCidade = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        lblCEPcliente = new javax.swing.JLabel();
        ftxCepCliente = new javax.swing.JFormattedTextField();
        txtCidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnConsultarNome = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuConsultaNome = new javax.swing.JMenuItem();
        mnuConsultarCPF = new javax.swing.JMenuItem();
        mnuSalvarCliente = new javax.swing.JMenuItem();
        mnuExcluirCliente = new javax.swing.JMenuItem();
        mnuAlterarCliente = new javax.swing.JMenuItem();
        mnuLimpar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rede Farmácia - Cadastro Cliente");
        setName("Frame Cadastro Cliente"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro do cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblName.setText("Nome*:");

        txtNome.setName("NOME"); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        lblCPF.setText("CPF*:");

        try {
            ftxCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCPF.setName("CPF"); // NOI18N
        ftxCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxCPFFocusLost(evt);
            }
        });
        ftxCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxCPFKeyTyped(evt);
            }
        });

        btnConsultarCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zoom-icon.png"))); // NOI18N
        btnConsultarCPF.setText("Consulta por CPF");
        btnConsultarCPF.setDoubleBuffered(true);
        btnConsultarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCPFActionPerformed(evt);
            }
        });

        lblGenero.setText("Gênero*:");

        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não especificado", "Masculino", "Feminino" }));
        cboGenero.setName("GÊNERO"); // NOI18N

        lblEndereco.setText("Endereço*:");

        txtEndereco.setName("ENDEREÇO"); // NOI18N
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyTyped(evt);
            }
        });

        lblTelefone.setText("Telefone:");
        lblTelefone.setName("TELEFONE"); // NOI18N

        try {
            ftxTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxTelefone.setName("TELEFONE"); // NOI18N
        ftxTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxTelefoneFocusLost(evt);
            }
        });
        ftxTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxTelefoneKeyTyped(evt);
            }
        });

        lblBairro.setText("Bairro*:");

        txtBairro.setName("BAIRRO"); // NOI18N
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });

        lblEstadoCivil.setText("Estado Civil:");

        cboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não informado", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "União Estável" }));
        cboEstadoCivil.setName("ESTADO CIVIL"); // NOI18N

        lblDataNascimento.setText("Data Nasc.:");
        lblDataNascimento.setName("DATA DE NASCIMENTO"); // NOI18N

        lblEmail.setText("E-mail*:");

        txtEmail.setName("E-MAIL"); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        lblEstado.setText("Estado*:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cboEstado.setName("ESTADO"); // NOI18N

        lblCidade.setText("Cidade*: ");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-icon.png"))); // NOI18N
        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alterar.png"))); // NOI18N
        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        lblCEPcliente.setText("CEP*:");

        try {
            ftxCepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCepCliente.setName("CEP"); // NOI18N
        ftxCepCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxCepClienteFocusLost(evt);
            }
        });
        ftxCepCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxCepClienteKeyTyped(evt);
            }
        });

        txtCidade.setName("CIDADE"); // NOI18N
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCidadeKeyReleased(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Gênero", "E.Civil", "Telefone", "Data Nasc.", "E-mail", "Endereço", "Bairro", "Cidade", "Estado", "CEP"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        btnConsultarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zoom-icon.png"))); // NOI18N
        btnConsultarNome.setText("Consulta por nome");
        btnConsultarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarNomeActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(lblEstadoCivil)
                    .addComponent(lblBairro)
                    .addComponent(lblEndereco)
                    .addComponent(lblGenero)
                    .addComponent(lblCPF)
                    .addComponent(lblName)
                    .addComponent(lblCidade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboGenero, 0, 302, Short.MAX_VALUE)
                            .addComponent(cboEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDataNascimento)
                            .addComponent(lblTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblEstado)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblCEPcliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ftxCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(ftxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnConsultarCPF)
                            .addGap(18, 18, 18)
                            .addComponent(btnConsultarNome))
                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnExcluirCliente)
                            .addGap(18, 18, 18)
                            .addComponent(btnAlterarCliente)
                            .addGap(18, 18, 18)
                            .addComponent(btnLimpar))))
                .addGap(90, 90, 90))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterarCliente, btnExcluirCliente, btnLimpar, btnSalvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBairro, txtCidade});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnConsultarCPF, btnConsultarNome});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftxTelefone, jDateChooser1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(ftxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCPF)
                    .addComponent(btnConsultarNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGenero)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelefone)
                        .addComponent(ftxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstadoCivil)
                        .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDataNascimento))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCEPcliente)
                    .addComponent(ftxCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCidade)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstado)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluirCliente)
                    .addComponent(btnAlterarCliente)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboEstado, ftxCPF, ftxCepCliente, jDateChooser1, txtBairro, txtCidade, txtEmail, txtEndereco, txtNome});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterarCliente, btnExcluirCliente, btnLimpar, btnSalvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConsultarCPF, btnConsultarNome});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboEstadoCivil, cboGenero, ftxTelefone});

        txtCidade.getAccessibleContext().setAccessibleName("CIDADE");

        mnuArquivo.setText("Arquivo");

        mnuConsultaNome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsultaNome.setText("Consultar Nome");
        mnuConsultaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaNomeActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuConsultaNome);

        mnuConsultarCPF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsultarCPF.setText("Consultar CPF");
        mnuConsultarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarCPFActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuConsultarCPF);

        mnuSalvarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalvarCliente.setText("Salvar");
        mnuSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalvarClienteActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuSalvarCliente);

        mnuExcluirCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuExcluirCliente.setText("Excluir");
        mnuExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExcluirClienteActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuExcluirCliente);

        mnuAlterarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuAlterarCliente.setText("Alterar");
        mnuAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlterarClienteActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuAlterarCliente);

        mnuLimpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuLimpar.setText("Limpar Campos");
        mnuLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLimparActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuLimpar);
        mnuArquivo.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Log-Out-icon.png"))); // NOI18N
        mnuSair.setText("Fechar");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuSair);

        jMenuBar1.add(mnuArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed


    private void mnuSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalvarClienteActionPerformed
        Validadora validador = new Validadora();
        validador.ValidarCPF(ftxCPF);
        validador.ValidarCEP(ftxCepCliente);

        //validando campos de texto
        validador.ValidarTexto(txtNome);
        validador.ValidarTexto(txtEndereco);
        validador.ValidarTexto(txtEmail);
        validador.ValidarTexto(txtBairro);
        validador.ValidarTexto(txtCidade);

        //validando campos de combo box
        validador.ValidarComboBox(cboGenero);
        validador.ValidarComboBox(cboEstado);

        if (validador.hasErro()) {
            JOptionPane.showMessageDialog(this, validador.getMensagensErro());
        } else {
            if (modoTela == "criação") {

                String CPF = ftxCPF.getText();
                String nome = txtNome.getText();
                String genero = cboGenero.getSelectedItem().toString();
                String estadoCivil = cboEstadoCivil.getSelectedItem().toString();
                String telefone = ftxTelefone.getText();
                Date dtNascimento = jDateChooser1.getDate();
//String dtNascimento = ftxNascimento.getText();
                String email = txtEmail.getText();
                String endereco = txtEndereco.getText();
                String bairro = txtBairro.getText();
                String cidade = txtCidade.getText();
                String estado = cboEstado.getSelectedItem().toString();
                String CEP = ftxCepCliente.getText();

                boolean retorno = ClienteController.salvar(CPF, nome, genero, estadoCivil, telefone, dtNascimento,
                        email, endereco, bairro, cidade, estado, CEP);

                if (retorno == true) {
                    JOptionPane.showMessageDialog(null, "Cliente CADASTRADO com sucesso!",
                            "Cadastro realizado", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(null, "Falha no cadastro do cliente!",
                            "Falha", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                //MODO ALTERAÇÃO BOTAO ALTERAR
                int id = objCliente.getId();

                String CPF = ftxCPF.getText();
                String nome = txtNome.getText();
                String genero = cboGenero.getSelectedItem().toString();
                String estadoCivil = cboEstadoCivil.getSelectedItem().toString();
                String telefone = ftxTelefone.getText();
                Date dtNascimento = jDateChooser1.getDate();
//String dtNascimento = ftxNascimento.getText(); //fazer jCalendar
                String email = txtEmail.getText();
                String endereco = txtEndereco.getText();
                String bairro = txtBairro.getText();
                String cidade = txtCidade.getText();
                String estado = cboEstado.getSelectedItem().toString();
                String CEP = ftxCepCliente.getText();

                boolean retorno = ClienteController.atualizar(id, CPF, nome, genero, estadoCivil, telefone, dtNascimento,
                        email, endereco, bairro, cidade, estado, CEP);

                if (retorno == true) {
                    JOptionPane.showMessageDialog(null, "Cliente ALTERADO com sucesso!",
                            "Cadastro realizado", JOptionPane.INFORMATION_MESSAGE);
                    modoTela = "criação";
                } else {
                    JOptionPane.showMessageDialog(null, "Falha na ALTERAÇÃO de cliente!",
                            "Falha", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
        listarClientes();
    }//GEN-LAST:event_mnuSalvarClienteActionPerformed

    private void mnuAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlterarClienteActionPerformed
        if (tblCliente.getRowCount() > 0) {
            int numeroLinha = tblCliente.getSelectedRow();

            if (numeroLinha < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um cliente da tabela!");
            } else {

                int IDcliente = Integer.parseInt(tblCliente.getModel().getValueAt(numeroLinha, 0).toString());

                String CPF = tblCliente.getModel().getValueAt(numeroLinha, 1).toString();
                String nome = tblCliente.getModel().getValueAt(numeroLinha, 2).toString();
                String genero = tblCliente.getModel().getValueAt(numeroLinha, 3).toString();
                String estadoCivil = tblCliente.getModel().getValueAt(numeroLinha, 4).toString();
                String telefone = tblCliente.getModel().getValueAt(numeroLinha, 5).toString();
                String dtNascimento = tblCliente.getModel().getValueAt(numeroLinha, 6).toString(); //fazer jCalendar
                String email = tblCliente.getModel().getValueAt(numeroLinha, 7).toString();
                String endereco = tblCliente.getModel().getValueAt(numeroLinha, 8).toString();
                String bairro = tblCliente.getModel().getValueAt(numeroLinha, 9).toString();
                String cidade = tblCliente.getModel().getValueAt(numeroLinha, 10).toString();
                String estado = tblCliente.getModel().getValueAt(numeroLinha, 11).toString();
                String CEP = tblCliente.getModel().getValueAt(numeroLinha, 12).toString();

                objCliente.setId(IDcliente);
                ftxCPF.setText(CPF);
                txtNome.setText(nome);
                ftxTelefone.setText(telefone);
                //ftxNascimento.setText(dtNascimento);
                txtEmail.setText(email);
                txtEndereco.setText(endereco);
                txtBairro.setText(bairro);
                txtCidade.setText(cidade);
                cboEstado.setName(estado);
                ftxCepCliente.setText(CEP);

                if (genero.equals("Masculino")) {
                    cboGenero.setSelectedIndex(1);
                } else if (genero.equals("Feminino")) {
                    cboGenero.setSelectedIndex(2);
                }

                if (estadoCivil.equals("Solteiro(a)")) {
                    cboEstadoCivil.setSelectedIndex(1);
                } else if (estadoCivil.equals("Casado(a)")) {
                    cboEstadoCivil.setSelectedIndex(2);
                } else if (estadoCivil.equals("Divorciado(a)")) {
                    cboEstadoCivil.setSelectedIndex(3);
                } else if (estadoCivil.equals("União Estável")) {
                    cboEstadoCivil.setSelectedIndex(4);
                }

                if (estado.equals("AC")) {
                    cboEstado.setSelectedIndex(1);
                } else if (estado.equals("AL")) {
                    cboEstado.setSelectedIndex(2);
                } else if (estado.equals("AP")) {
                    cboEstado.setSelectedIndex(3);
                } else if (estado.equals("AM")) {
                    cboEstado.setSelectedIndex(4);
                } else if (estado.equals("BA")) {
                    cboEstado.setSelectedIndex(5);
                } else if (estado.equals("CE")) {
                    cboEstado.setSelectedIndex(6);
                } else if (estado.equals("DF")) {
                    cboEstado.setSelectedIndex(7);
                } else if (estado.equals("ES")) {
                    cboEstado.setSelectedIndex(8);
                } else if (estado.equals("GO")) {
                    cboEstado.setSelectedIndex(9);
                } else if (estado.equals("MA")) {
                    cboEstado.setSelectedIndex(10);
                } else if (estado.equals("MT")) {
                    cboEstado.setSelectedIndex(11);
                } else if (estado.equals("MG")) {
                    cboEstado.setSelectedIndex(12);
                } else if (estado.equals("PA")) {
                    cboEstado.setSelectedIndex(13);
                } else if (estado.equals("PB")) {
                    cboEstado.setSelectedIndex(14);
                } else if (estado.equals("PR")) {
                    cboEstado.setSelectedIndex(15);
                } else if (estado.equals("PE")) {
                    cboEstado.setSelectedIndex(16);
                } else if (estado.equals("PI")) {
                    cboEstado.setSelectedIndex(17);
                } else if (estado.equals("RJ")) {
                    cboEstado.setSelectedIndex(18);
                } else if (estado.equals("RN")) {
                    cboEstado.setSelectedIndex(19);
                } else if (estado.equals("RS")) {
                    cboEstado.setSelectedIndex(20);
                } else if (estado.equals("RO")) {
                    cboEstado.setSelectedIndex(21);
                } else if (estado.equals("RR")) {
                    cboEstado.setSelectedIndex(22);
                } else if (estado.equals("SC")) {
                    cboEstado.setSelectedIndex(23);
                } else if (estado.equals("SP")) {
                    cboEstado.setSelectedIndex(24);
                } else if (estado.equals("SE")) {
                    cboEstado.setSelectedIndex(25);
                } else if (estado.equals("TO")) {
                    cboEstado.setSelectedIndex(26);
                }

                modoTela = "alteracao";
                //aqui muda o "formato" da tela que permite a alteração pelo botão salvar sem precisar de duas telas

            }
        }
    }//GEN-LAST:event_mnuAlterarClienteActionPerformed

    private void mnuConsultaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaNomeActionPerformed

        ArrayList<String[]> filtro = ClienteController.filtroNome(txtNome.getText());

        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        modelo.setRowCount(0);

        for (String[] item : filtro) {
            modelo.addRow(item);
        }

        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(10); //id
        tblCliente.getColumnModel().getColumn(1).setPreferredWidth(50); //CPF
        tblCliente.getColumnModel().getColumn(2).setPreferredWidth(50); //nome
        tblCliente.getColumnModel().getColumn(3).setPreferredWidth(30); //Genero
        tblCliente.getColumnModel().getColumn(4).setPreferredWidth(50); //E. Civil
        tblCliente.getColumnModel().getColumn(5).setPreferredWidth(50); //Telefone
        tblCliente.getColumnModel().getColumn(6).setPreferredWidth(50); //data nascimento
        tblCliente.getColumnModel().getColumn(7).setPreferredWidth(50); //e-mail
        tblCliente.getColumnModel().getColumn(8).setPreferredWidth(50); //endereço
        tblCliente.getColumnModel().getColumn(9).setPreferredWidth(50); //bairro
        tblCliente.getColumnModel().getColumn(10).setPreferredWidth(50); //cidade
        tblCliente.getColumnModel().getColumn(11).setPreferredWidth(10); //estado
        tblCliente.getColumnModel().getColumn(12).setPreferredWidth(50); //CEP
    }//GEN-LAST:event_mnuConsultaNomeActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void btnConsultarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCPFActionPerformed
        Validadora validador = new Validadora();
        validador.ValidarCPF(ftxCPF);

        if (validador.hasErro()) {
            JOptionPane.showMessageDialog(this, validador.getMensagensErro());
        } else {

            ArrayList<String[]> filtro = ClienteController.filtroCPF(ftxCPF.getText());

            DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
            modelo.setRowCount(0);

            for (String[] item : filtro) {
                modelo.addRow(item);
            }
        }
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(10); //id
        tblCliente.getColumnModel().getColumn(1).setPreferredWidth(50); //CPF
        tblCliente.getColumnModel().getColumn(2).setPreferredWidth(50); //nome
        tblCliente.getColumnModel().getColumn(3).setPreferredWidth(30); //Genero
        tblCliente.getColumnModel().getColumn(4).setPreferredWidth(50); //E. Civil
        tblCliente.getColumnModel().getColumn(5).setPreferredWidth(50); //Telefone
        tblCliente.getColumnModel().getColumn(6).setPreferredWidth(50); //data nascimento
        tblCliente.getColumnModel().getColumn(7).setPreferredWidth(50); //e-mail
        tblCliente.getColumnModel().getColumn(8).setPreferredWidth(50); //endereço
        tblCliente.getColumnModel().getColumn(9).setPreferredWidth(50); //bairro
        tblCliente.getColumnModel().getColumn(10).setPreferredWidth(50); //cidade
        tblCliente.getColumnModel().getColumn(11).setPreferredWidth(10); //estado
        tblCliente.getColumnModel().getColumn(12).setPreferredWidth(50); //CEP

    }//GEN-LAST:event_btnConsultarCPFActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Validadora validador = new Validadora();
        validador.ValidarCPF(ftxCPF);
        validador.ValidarCEP(ftxCepCliente);

        //validando campos de texto
        validador.ValidarTexto(txtNome);
        validador.ValidarTexto(txtEndereco);
        validador.ValidarTexto(txtEmail);
        validador.ValidarTexto(txtBairro);
        validador.ValidarTexto(txtCidade);

        //validando campos de combo box
        validador.ValidarComboBox(cboGenero);
        validador.ValidarComboBox(cboEstado);

        if (validador.hasErro()) {
            JOptionPane.showMessageDialog(this, validador.getMensagensErro());
        } else {
            if (modoTela == "criação") {

                String CPF = ftxCPF.getText();
                String nome = txtNome.getText();
                String genero = cboGenero.getSelectedItem().toString();
                String estadoCivil = cboEstadoCivil.getSelectedItem().toString();
                String telefone = ftxTelefone.getText();
                Date dtNascimento = jDateChooser1.getDate();
                //String dtNascimento = ftxNascimento.getText();
                String email = txtEmail.getText();
                String endereco = txtEndereco.getText();
                String bairro = txtBairro.getText();
                String cidade = txtCidade.getText();
                String estado = cboEstado.getSelectedItem().toString();
                String CEP = ftxCepCliente.getText();

                boolean retorno = ClienteController.salvar(CPF, nome, genero, estadoCivil, telefone, dtNascimento,
                        email, endereco, bairro, cidade, estado, CEP);

                if (retorno == true) {
                    JOptionPane.showMessageDialog(null, "Cliente CADASTRADO com sucesso!",
                            "Cadastro realizado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Falha no cadastro do cliente!",
                            "Falha", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                //MODO ALTERAÇÃO BOTAO ALTERAR
                int id = objCliente.getId();

                String CPF = ftxCPF.getText();
                String nome = txtNome.getText();
                String genero = cboGenero.getSelectedItem().toString();
                String estadoCivil = cboEstadoCivil.getSelectedItem().toString();
                String telefone = ftxTelefone.getText();
                Date dtNascimento = jDateChooser1.getDate();
                //String dtNascimento = ftxNascimento.getText(); //fazer jCalendar
                String email = txtEmail.getText();
                String endereco = txtEndereco.getText();
                String bairro = txtBairro.getText();
                String cidade = txtCidade.getText();
                String estado = cboEstado.getSelectedItem().toString();
                String CEP = ftxCepCliente.getText();

                boolean retorno = ClienteController.atualizar(id, CPF, nome, genero, estadoCivil, telefone, dtNascimento,
                        email, endereco, bairro, cidade, estado, CEP);

                if (retorno == true) {
                    JOptionPane.showMessageDialog(null, "Cliente ALTERADO com sucesso!",
                            "Cadastro realizado", JOptionPane.INFORMATION_MESSAGE);
                    modoTela = "criação";
                } else {
                    JOptionPane.showMessageDialog(null, "Falha na ALTERAÇÃO de cliente!",
                            "Falha", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
        listarClientes();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if (txtNome.getText().length() > 40) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Máximo de 40 caracteres antingidos para o campo nome!");
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        String textoAnterior = txtNome.getText();
        txtNome.setText(textoAnterior.toUpperCase());

    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if (txtEmail.getText().length() > 40) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Máximo de 40 caracteres antingidos para o campo e-mail!");
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        //não colocar nada, abri por engano.
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyTyped
        if (txtEndereco.getText().length() > 60) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Máximo de 60 caracteres antingidos para o campo endereço!");
        }
    }//GEN-LAST:event_txtEnderecoKeyTyped

    private void txtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyReleased
        String textoAnterior = txtEndereco.getText();
        txtEndereco.setText(textoAnterior.toUpperCase());
    }//GEN-LAST:event_txtEnderecoKeyReleased

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
        if (txtBairro.getText().length() > 20) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Máximo de 20 caracteres antingidos para o campo bairo!");
        }
    }//GEN-LAST:event_txtBairroKeyTyped

    private void txtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyReleased
        String textoAnterior = txtBairro.getText();
        txtBairro.setText(textoAnterior.toUpperCase());
    }//GEN-LAST:event_txtBairroKeyReleased

    private void ftxCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxCPFKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Somente números.");
        }
    }//GEN-LAST:event_ftxCPFKeyTyped

    private void ftxTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxTelefoneKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Somente números.");
        }
    }//GEN-LAST:event_ftxTelefoneKeyTyped

    private void ftxCepClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxCepClienteKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Somente números.");
        }
    }//GEN-LAST:event_ftxCepClienteKeyTyped

    private void ftxCepClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxCepClienteFocusLost
    }//GEN-LAST:event_ftxCepClienteFocusLost

    private void ftxTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxTelefoneFocusLost

    }//GEN-LAST:event_ftxTelefoneFocusLost

    private void ftxCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxCPFFocusLost

    }//GEN-LAST:event_ftxCPFFocusLost

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void mnuConsultarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarCPFActionPerformed
        Validadora validador = new Validadora();
        validador.ValidarCPF(ftxCPF);

        if (validador.hasErro()) {
            JOptionPane.showMessageDialog(this, validador.getMensagensErro());
        } else {

            ArrayList<String[]> filtro = ClienteController.filtroCPF(ftxCPF.getText());

            DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
            modelo.setRowCount(0);

            for (String[] item : filtro) {
                modelo.addRow(item);
            }
        }
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(10); //id
        tblCliente.getColumnModel().getColumn(1).setPreferredWidth(50); //CPF
        tblCliente.getColumnModel().getColumn(2).setPreferredWidth(50); //nome
        tblCliente.getColumnModel().getColumn(3).setPreferredWidth(30); //Genero
        tblCliente.getColumnModel().getColumn(4).setPreferredWidth(50); //E. Civil
        tblCliente.getColumnModel().getColumn(5).setPreferredWidth(50); //Telefone
        tblCliente.getColumnModel().getColumn(6).setPreferredWidth(50); //data nascimento
        tblCliente.getColumnModel().getColumn(7).setPreferredWidth(50); //e-mail
        tblCliente.getColumnModel().getColumn(8).setPreferredWidth(50); //endereço
        tblCliente.getColumnModel().getColumn(9).setPreferredWidth(50); //bairro
        tblCliente.getColumnModel().getColumn(10).setPreferredWidth(50); //cidade
        tblCliente.getColumnModel().getColumn(11).setPreferredWidth(10); //estado
        tblCliente.getColumnModel().getColumn(12).setPreferredWidth(50); //CEP
    }//GEN-LAST:event_mnuConsultarCPFActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.ftxCPF.setText("");
        this.txtNome.setText("");
        this.cboGenero.setSelectedIndex(0);
        this.cboEstadoCivil.setSelectedIndex(0);
        this.ftxTelefone.setText("");
        //this.jDateChooser1.setDate();
        //this.jDateChooser1.setDateFormatString("");
        //this.ftxNascimento.setText("");
        this.txtEmail.setText("");
        this.txtEndereco.setText("");
        this.txtBairro.setText("");
        this.txtCidade.setText("");
        this.cboEstado.setSelectedIndex(0);
        this.ftxCepCliente.setText("");
        listarClientes();
        modoTela = "criação";

    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyReleased
        String textoAnterior = txtCidade.getText();
        txtCidade.setText(textoAnterior.toUpperCase());
    }//GEN-LAST:event_txtCidadeKeyReleased

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        if (tblCliente.getRowCount() > 0) {
            int numeroLinha = tblCliente.getSelectedRow();
            if (numeroLinha < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um cliente para excluir!");
            } else {

                int IDcliente = Integer.parseInt(tblCliente.getModel().getValueAt(numeroLinha, 0).toString());
                objCliente.setId(IDcliente);
                int id = objCliente.getId();
                boolean retorno = ClienteController.excluir(id);

                if (retorno == true) {
                    JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao excluir cliente!");
                }

                listarClientes();

            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há clientes cadastrados!");
        }

    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed

        if (tblCliente.getRowCount() > 0) {
            int numeroLinha = tblCliente.getSelectedRow();

            if (numeroLinha < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um cliente da tabela!");
            } else {

                int IDcliente = Integer.parseInt(tblCliente.getModel().getValueAt(numeroLinha, 0).toString());

                String CPF = tblCliente.getModel().getValueAt(numeroLinha, 1).toString();
                String nome = tblCliente.getModel().getValueAt(numeroLinha, 2).toString();
                String genero = tblCliente.getModel().getValueAt(numeroLinha, 3).toString();
                String estadoCivil = tblCliente.getModel().getValueAt(numeroLinha, 4).toString();
                String telefone = tblCliente.getModel().getValueAt(numeroLinha, 5).toString();
                String email = tblCliente.getModel().getValueAt(numeroLinha, 7).toString();
                String endereco = tblCliente.getModel().getValueAt(numeroLinha, 8).toString();
                String bairro = tblCliente.getModel().getValueAt(numeroLinha, 9).toString();
                String cidade = tblCliente.getModel().getValueAt(numeroLinha, 10).toString();
                String estado = tblCliente.getModel().getValueAt(numeroLinha, 11).toString();
                String CEP = tblCliente.getModel().getValueAt(numeroLinha, 12).toString();

                try {

                    String dataNasc = tblCliente.getModel().getValueAt(numeroLinha, 6).toString();
                    Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(dataNasc);
                    System.out.println(date1);
                    java.util.Date hoje = new java.util.Date();
                    System.out.println(hoje);
                    jDateChooser1.setDate(date1);

                } catch (ParseException ex) {
                    Logger.getLogger(CadastroClienteView.class.getName()).log(Level.SEVERE, null, ex);
                }

                objCliente.setId(IDcliente);
                ftxCPF.setText(CPF);
                txtNome.setText(nome);
                ftxTelefone.setText(telefone);
                txtEmail.setText(email);
                txtEndereco.setText(endereco);
                txtBairro.setText(bairro);
                txtCidade.setText(cidade);
                cboEstado.setName(estado);
                ftxCepCliente.setText(CEP);

                if (genero.equals("Masculino")) {
                    cboGenero.setSelectedIndex(1);
                } else if (genero.equals("Feminino")) {
                    cboGenero.setSelectedIndex(2);
                }

                if (estadoCivil.equals("Solteiro(a)")) {
                    cboEstadoCivil.setSelectedIndex(1);
                } else if (estadoCivil.equals("Casado(a)")) {
                    cboEstadoCivil.setSelectedIndex(2);
                } else if (estadoCivil.equals("Divorciado(a)")) {
                    cboEstadoCivil.setSelectedIndex(3);
                } else if (estadoCivil.equals("União Estável")) {
                    cboEstadoCivil.setSelectedIndex(4);
                }

                if (estado.equals("AC")) {
                    cboEstado.setSelectedIndex(1);
                } else if (estado.equals("AL")) {
                    cboEstado.setSelectedIndex(2);
                } else if (estado.equals("AP")) {
                    cboEstado.setSelectedIndex(3);
                } else if (estado.equals("AM")) {
                    cboEstado.setSelectedIndex(4);
                } else if (estado.equals("BA")) {
                    cboEstado.setSelectedIndex(5);
                } else if (estado.equals("CE")) {
                    cboEstado.setSelectedIndex(6);
                } else if (estado.equals("DF")) {
                    cboEstado.setSelectedIndex(7);
                } else if (estado.equals("ES")) {
                    cboEstado.setSelectedIndex(8);
                } else if (estado.equals("GO")) {
                    cboEstado.setSelectedIndex(9);
                } else if (estado.equals("MA")) {
                    cboEstado.setSelectedIndex(10);
                } else if (estado.equals("MT")) {
                    cboEstado.setSelectedIndex(11);
                } else if (estado.equals("MG")) {
                    cboEstado.setSelectedIndex(12);
                } else if (estado.equals("PA")) {
                    cboEstado.setSelectedIndex(13);
                } else if (estado.equals("PB")) {
                    cboEstado.setSelectedIndex(14);
                } else if (estado.equals("PR")) {
                    cboEstado.setSelectedIndex(15);
                } else if (estado.equals("PE")) {
                    cboEstado.setSelectedIndex(16);
                } else if (estado.equals("PI")) {
                    cboEstado.setSelectedIndex(17);
                } else if (estado.equals("RJ")) {
                    cboEstado.setSelectedIndex(18);
                } else if (estado.equals("RN")) {
                    cboEstado.setSelectedIndex(19);
                } else if (estado.equals("RS")) {
                    cboEstado.setSelectedIndex(20);
                } else if (estado.equals("RO")) {
                    cboEstado.setSelectedIndex(21);
                } else if (estado.equals("RR")) {
                    cboEstado.setSelectedIndex(22);
                } else if (estado.equals("SC")) {
                    cboEstado.setSelectedIndex(23);
                } else if (estado.equals("SP")) {
                    cboEstado.setSelectedIndex(24);
                } else if (estado.equals("SE")) {
                    cboEstado.setSelectedIndex(25);
                } else if (estado.equals("TO")) {
                    cboEstado.setSelectedIndex(26);
                }

                modoTela = "alteracao";
                //aqui muda o "formato" da tela que permite a alteração pelo botão salvar sem precisar de duas telas

            }
        }
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnConsultarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarNomeActionPerformed

        ArrayList<String[]> filtro = ClienteController.filtroNome(txtNome.getText());

        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        modelo.setRowCount(0);

        for (String[] item : filtro) {
            modelo.addRow(item);
        }

        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(10); //id
        tblCliente.getColumnModel().getColumn(1).setPreferredWidth(50); //CPF
        tblCliente.getColumnModel().getColumn(2).setPreferredWidth(50); //nome
        tblCliente.getColumnModel().getColumn(3).setPreferredWidth(30); //Genero
        tblCliente.getColumnModel().getColumn(4).setPreferredWidth(50); //E. Civil
        tblCliente.getColumnModel().getColumn(5).setPreferredWidth(50); //Telefone
        tblCliente.getColumnModel().getColumn(6).setPreferredWidth(50); //data nascimento
        tblCliente.getColumnModel().getColumn(7).setPreferredWidth(50); //e-mail
        tblCliente.getColumnModel().getColumn(8).setPreferredWidth(50); //endereço
        tblCliente.getColumnModel().getColumn(9).setPreferredWidth(50); //bairro
        tblCliente.getColumnModel().getColumn(10).setPreferredWidth(50); //cidade
        tblCliente.getColumnModel().getColumn(11).setPreferredWidth(10); //estado
        tblCliente.getColumnModel().getColumn(12).setPreferredWidth(50); //CEP


    }//GEN-LAST:event_btnConsultarNomeActionPerformed

    private void mnuLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLimparActionPerformed
        this.ftxCPF.setText("");
        this.txtNome.setText("");
        this.cboGenero.setSelectedIndex(0);
        this.cboEstadoCivil.setSelectedIndex(0);
        this.ftxTelefone.setText("");
        this.jDateChooser1.setDateFormatString("");
        //this.ftxNascimento.setText("");
        this.txtEmail.setText("");
        this.txtEndereco.setText("");
        this.txtBairro.setText("");
        this.txtCidade.setText("");
        this.cboEstado.setSelectedIndex(0);
        this.ftxCepCliente.setText("");
        listarClientes();
        modoTela = "criação";
    }//GEN-LAST:event_mnuLimparActionPerformed

    private void mnuExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExcluirClienteActionPerformed
        if (tblCliente.getRowCount() > 0) {

            int numeroLinha = tblCliente.getSelectedRow();

            if (numeroLinha < 0) {

                JOptionPane.showMessageDialog(this, "Selecione um cliente para excluir!");

            } else {

                int IDcliente = Integer.parseInt(tblCliente.getModel().getValueAt(numeroLinha, 0).toString());
                objCliente.setId(IDcliente);
                int id = objCliente.getId();
                boolean retorno = ClienteController.excluir(id);

                if (retorno == true) {
                    JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao excluir cliente!");
                }

                listarClientes();

            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há clientes cadastrados!");
        }
    }//GEN-LAST:event_mnuExcluirClienteActionPerformed

    public void listarClientes() {
        //lista toda a base de dados daquela tabela
        ArrayList<String[]> listaCliente = ClienteController.listarC();

        DefaultTableModel tmCliente = new DefaultTableModel();
        tmCliente.addColumn("ID");
        tmCliente.addColumn("CPF");
        tmCliente.addColumn("Nome");
        tmCliente.addColumn("Genero");
        tmCliente.addColumn("E. Civil");
        tmCliente.addColumn("Telefone");
        tmCliente.addColumn("D. Nasc.");
        tmCliente.addColumn("E-mail");
        tmCliente.addColumn("Endereço");
        tmCliente.addColumn("Bairro");
        tmCliente.addColumn("Cidade");
        tmCliente.addColumn("Estado");
        tmCliente.addColumn("CEP");

        tblCliente.setModel(tmCliente);
        tmCliente.setRowCount(0);

        for (String[] item : listaCliente) {
            tmCliente.addRow(item);

        }

        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(10); //id
        tblCliente.getColumnModel().getColumn(1).setPreferredWidth(50); //CPF
        tblCliente.getColumnModel().getColumn(2).setPreferredWidth(50); //nome
        tblCliente.getColumnModel().getColumn(3).setPreferredWidth(30); //Genero
        tblCliente.getColumnModel().getColumn(4).setPreferredWidth(50); //E. Civil
        tblCliente.getColumnModel().getColumn(5).setPreferredWidth(50); //Telefone
        tblCliente.getColumnModel().getColumn(6).setPreferredWidth(50); //data nascimento
        tblCliente.getColumnModel().getColumn(7).setPreferredWidth(50); //e-mail
        tblCliente.getColumnModel().getColumn(8).setPreferredWidth(50); //endereço
        tblCliente.getColumnModel().getColumn(9).setPreferredWidth(50); //bairro
        tblCliente.getColumnModel().getColumn(10).setPreferredWidth(50); //cidade
        tblCliente.getColumnModel().getColumn(11).setPreferredWidth(10); //estado
        tblCliente.getColumnModel().getColumn(12).setPreferredWidth(50); //CEP

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Windows look and feel?
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnConsultarCPF;
    private javax.swing.JButton btnConsultarNome;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboEstadoCivil;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JFormattedTextField ftxCPF;
    private javax.swing.JFormattedTextField ftxCepCliente;
    private javax.swing.JFormattedTextField ftxTelefone;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEPcliente;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JMenuItem mnuAlterarCliente;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenuItem mnuConsultaNome;
    private javax.swing.JMenuItem mnuConsultarCPF;
    private javax.swing.JMenuItem mnuExcluirCliente;
    private javax.swing.JMenuItem mnuLimpar;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuSalvarCliente;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
